sudo: required
dist: trusty
services:
- docker
before_install:
- docker pull thomasweise/docker-pandoc
- mkdir _build
script:
- docker run -v $(pwd):/data --rm thomasweise/docker-pandoc data/build.sh
- "./check-links.sh"
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: U4/BguyLVr6nZydDIPzDWvamohtArMhZZ74C8KXg2vsZn1AOSHFAaNjh03ePTc+SuxmY/Do7UU9Ms/Pw0XjG6H3MHv2mps0/0dzd/kifznFcZgzSJiG51Wl+iTE++dqKi/0kRh/Jr2zrEN3EyR80tF8+Awnie6Vc2LYlVsjZNNDY45cfNQQknOYVMj0mXxCtzp2jovhEflu+zMxAzvDQn2sUAdUJJQMBGgjwlB+DCCkIFo/AuWOUWIYIaVT2aWLj/1hAll1WOHJNwsKAUzsPhHF65tbjWdQOeyzk1vN1IOCn17tGxs2FHSZzgQ9CfI4Z2KIVCCBcSMO78mMIHgHveAEWe4A5hri1DO/ZGSMw8AmBXaGSEUnLJTdYVeGLMIHQS4P4FZ4Umfn9tbw7AciYg5SePf9B7xbOLauDKGYGj9d0iklY/z9w36tQcRr0WRzOikBaRX7MTuN8AaA4ShsUM0MX/JcbuV1wh9txTsl5favXUjogkrqJvja9jJ37yz3yQdZzrx5XYYc2LyrE5taOsVew8LBsdH9id3DZJTjKSJ3znZ/Uyf1LNbC4+vhtW3YiJkKSHaJHyFb+eYzuf/57exS0sLeRA6wkUJyYE7anRBGou2J/Sqaz8iZIp0SbpRg2EarYDZgyBEQps1Ysv8VvHpbhBuFzQSbPoQPTV6PEoWE=
  file: _build/databases.pdf
  skip_cleanup: true
  on:
    repo: michamos/RPP-online-hep-info
    tags: true
