name: Checks

on:
  - push
  - pull_request

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: check link validity
      uses: gaurav-nelson/github-action-markdown-link-check@v1
    - name: check link uniqueness
      if: always()
      run: |
        DUPLICATES=$(sed  -rn "s/.*[(<](https?[^)>]*).*/\1/p" README.md | sort | uniq -cd)
        if [[ $DUPLICATES ]]
        then
          echo "Found duplicate links:"
          echo "$DUPLICATES"
          exit 1
        else echo "No duplicates found"
        fi
